[package]
name = "teva"
version = "0.1.0"
description = "Adventure sandals for continuous git commits"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
